---
# tasks for roles/omego

- name: omego | install python virtualenv
  become: yes
  yum:
    name: python-virtualenv
    state: present

- name: omego | setup virtualenv
  become: yes
  pip:
    name: https://github.com/manics/omego/archive/db-check.zip
    state: present
    version: "{{ omero_omego_version | default(omit) }}"
    virtualenv: "{{ omero_common_basedir }}/omego"
    virtualenv_site_packages: yes
